### ISSUE TITLE
Problem with release 3.1 not working with 3.0 replay files

### ISSUE THREAD

**Issue by pnealgit** [Lux-AI-Challenge/Lux-Viewer-2021#43]
Hi Stone,

I get:
"Replay file works on version 3.1.x but client is on version 3.0.0. The visualizer will not be able to parse this replay file. Download an older visualizer with version 3.1.x here to watch the replay: https://github.com/Lux-AI-Challenge/LuxViewer2021/releases" 

coming up in the browser window.

and in the upper right-hand corner:

Replay Version: 3.1.0
Client Version: 3.0.0

I tried using 3.1.0 but there is no 'dist.zip' for it. 
I get the code, etc via a download of the .zip file 
but once I unpack it, there is no 'dist' directory.

I am not running on the Kaggle site because I want to run lots of
games and have my agent learn what to do.

Best regards,
Phil

**Comment by StoneT2000** [comment]
Do you not see a folder unpacked from https://github.com/Lux-AI-Challenge/Lux-Viewer-2021/releases/tag/v3.1.0 dist.zip file?

**Comment by StoneT2000** [comment]
Or temporarily you can also use 2021vis.lux-ai.org

**Comment by StoneT2000** [comment]
https://github.com/Lux-AI-Challenge/Lux-Viewer-2021/releases/tag/v3.1.0 should be updated now
