### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by condnsdmatters** [Lux-AI-Challenge/Lux-Viewer-2021#44]
Hi there,

Excellent work with both the Lux AI Challenge and the vizualiser! The project seems really neat. :)

I've noticed that the [Lux Design Engine](https://github.com/Lux-AI-Challenge/Lux-Design-2021) is under an [Apache License](https://github.com/Lux-AI-Challenge/Lux-Design-2021/blob/master/LICENSE) - but there isn't one here for the vizualiser. Is this under the same license?  If so, it might be useful for people looking to fork and customize the visualizations. 

Thanks, in advance.

**Comment by StoneT2000** [comment]
done :)
